---
name: Integration Tests
"on":
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  statuses: write
  actions: read
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Run integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Builds with a valid component ID
        uses: ./
        with:
          org_id: ${{ secrets.test_org_id }}
          api_token: ${{ secrets.test_api_token }}
          component_id: ${{ secrets.test_component_id }}
          api_url: ${{ secrets.test_api_url }}
