---
name: pull request checks
"on":
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  statuses: write
  actions: read
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  call-workflow-passing-data:
    uses: nuonco/.github/workflows/pull_request.yml@ja/3496-github-actions
    with:
      event_name: ${{ github.event_name }}
